modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "KNet BadPackets Backend"
authors = "Kneelawk"
description = "KNet Optional BadPackets Backend."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.4.148-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "knet_api"
type = "REQUIRED"
versionRange = "[1.1,)"
ordering = "NONE"
side = "BOTH"
