modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "KNet Example"
authors = "Kneelawk"
description = "KNet example mod."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.4.148-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "knet"
type = "REQUIRED"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
